"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.ISBN = exports.Livro = exports.Autor = exports.Editora = exports.Usuario = void 0;
const database_1 = require("../database");
const Usuarios_1 = __importDefault(require("./Usuarios"));
const Editoras_1 = __importDefault(require("./Editoras"));
const Autores_1 = __importDefault(require("./Autores"));
const Livros_1 = __importDefault(require("./Livros"));
const isbn_1 = __importDefault(require("./isbn"));
const Usuario = new Usuarios_1.default(database_1.mySqlConnection);
exports.Usuario = Usuario;
const Editora = new Editoras_1.default(database_1.mySqlConnection);
exports.Editora = Editora;
const Autor = new Autores_1.default(database_1.mySqlConnection);
exports.Autor = Autor;
const Livro = new Livros_1.default(database_1.mySqlConnection);
exports.Livro = Livro;
const ISBN = new isbn_1.default(database_1.mySqlConnection);
exports.ISBN = ISBN;
