DROP DATABASE IF EXISTS `MyBK`;
CREATE DATABASE `MyBK`;
USE `MyBK`;

CREATE TABLE `MyBK`.`usuarios` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`nome` VARCHAR(100) NOT NULL,
	`login` VARCHAR(50) NOT NULL,
	`senha` VARCHAR(100) NOT NULL,
	`createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  	`updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
		PRIMARY KEY(`id`)
) ENGINE = InnoDB DEFAULT CHARSET = latin1;

CREATE TABLE `MyBK`.`isbn` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`codigo` VARCHAR(200) NOT NULL,
	`createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  	`updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
		PRIMARY KEY(`id`)
) ENGINE = InnoDB DEFAULT CHARSET = latin1;


CREATE TABLE `MyBK`.`autores` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`nome` VARCHAR(100) NOT NULL,
	`total_livros` INT,
	`createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  	`updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
		PRIMARY KEY(`id`)
) ENGINE = InnoDB DEFAULT CHARSET = latin1;

CREATE TABLE `MyBK`.`editoras` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`nome` VARCHAR(100) NOT NULL,
	`total_livros` INT,
	`createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  	`updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
		PRIMARY KEY(`id`)
) ENGINE = InnoDB DEFAULT CHARSET = latin1;


CREATE TABLE `MyBK`.`livros` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`id_usuario` INT NOT NULL,
	`nome` VARCHAR(400) NOT NULL,
	`autor_id` INT NOT NULL,
	`editora_id` INT NOT NULL,
	`ano` VARCHAR(10) NOT NULL,
	`edicao` INT NOT NULL,
	`isbn_id` INT NOT NULL,
	`paginas` INT,
	`pagina_atual` INT,
	`restante` INT,
	`palavras_chave` VARCHAR(200),
	`rate` TINYINT,
	`createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  	`updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
		PRIMARY KEY(`id`),
		KEY `FK_usuario` (`id_usuario`),
		KEY `FK_autor` (`autor_id`),
		KEY `FK_editora` (`editora_id`),
		KEY `FK_isbn` (`isbn_id`),
		CONSTRAINT `FK_usuario` FOREIGN KEY(`id_usuario`) REFERENCES `usuarios` (`id`) ON DELETE CASCADE,
		CONSTRAINT `FK_autor` FOREIGN KEY (`autor_id`) REFERENCES `autores` (`id`) ON DELETE CASCADE, 
		CONSTRAINT `FK_editora` FOREIGN KEY (`editora_id`) REFERENCES `editoras` (`id`) ON DELETE CASCADE,
		CONSTRAINT `FK_isbn` FOREIGN KEY (`isbn_id`) REFERENCES `isbn` (`id`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = latin1;
